routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('/client', 'ClientController');
Route::resource('/document', 'DocumentController');

app/Client.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
  protected $fillable =['name_client','genre_client'];
  protected $guarded = ['id','created_at','update_at'];
  protected $table = 'clients';


  public function document(): BelongsTo
  {
      return $this->belongsTo('App\Document');
  }

}

app/Document.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Relations\HasOne;

use Illuminate\Database\Eloquent\Model;

class Document extends Model
{
    protected $fillable = ['type_document','number_document', 'document_client'];
    protected $guarded = ['id','created_at','update_at'];
    protected $table = 'documents';


    public function client(): HasOne
    {
        return $this->hasOne('App\Client');
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Client;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients = Client::all();
        $list = Client::all()->count();
        return view('client.index', compact('clients', 'list'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('client.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $client = new Client();
        $client->name_client = $request->name_client;
        $client->genre_client = $request->genre_client;
        $client->save();

        return redirect()->route('client.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id_client
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $client = Client::findOrFail($id);
        return view ('client.edit', compact('client'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $client = Client::findOrFail($id);
        $client->name_client = $request->name_client;
        $client->genre_client = $request->genre_client;
        $client->save();
        return redirect()->route('client.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $client = Client::findOrFail($id);
        $client->delete();
        return redirect()->route('client.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DocumentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Document;

class DocumentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $documents = Document::all();
        $list = Document::all()->count();
        return view('document.index', compact('documents', 'list'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('document.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $document = new Document();
        $document->type_document = $request->type_document;
        $document->number_document = $request->number_document;
        $document->document_client = $request->document_client;
        $document->save();

        return redirect()->route('document.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $document = Document::findOrFail($id);
        return view ('document.edit', compact('document'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $document = Document::findOrFail($id);
        $document->type_document = $request->type_document;
        $document->number_document = $request->number_document;
        $document->document_client = $request->document_client;
        $document->save();

        return redirect()->route('document.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $document = Document::findOrFail($id);
        $document->delete();
        return redirect()->route('document.index');
    }
}

resources/views/client/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <title>Crud Cliente</title>
</head>
<body>
  <div class="container">
    <div class="">
      <form action="{{route('client.store')}}" method="POST" enctype="multipart/form-data">
      {{ csrf_field() }}

          <div class="col-md-6">
            <div class="form-group">
              <h1>Cadastrar Cliente</h1>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label for="name_client">Nome</label>
              <input type="text" class="form-control" id="name_client" placeholder="Nome do Cliente" name="name_client">
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label for="genre_client">Gênero</label>
              <input type="text" class="form-control" id="genre_client" placeholder="Gênero do Cliente" name="genre_client">
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <button type="submit" class="btn btn-success">Salvar</button>
              <button class="btn btn-info" href="{{route('client.index')}}">Voltar</button>
            </div>
          </div>
      </form>
    </div>
  </div>
</body>
</html>

resources/views/client/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <title>Crud Cliente</title>
</head>
<body>
  <div class="container">
    <form method="post" action="{{route('client.update', $client->id)}}" enctype="multipart/form-data">
        {!! method_field('put') !!}
        {{ csrf_field() }}

        <div class="col-md-6">
          <div class="form-group">
            <h1>Cliente</h1>
          </div>
        </div>

        <!-- <input type="hidden" name="id_client" value="$client->id"> -->

        <div class="col-md-6">
          <div class="form-group">
            <label for="nome">Nome</label>
            <input type="text" class="form-control" id="name_client" name="name_client" value="{{$client->name_client}}">
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label for="autor">Autor</label>
            <input type="text" class="form-control" id="genre_client" name="genre_client" value="{{$client->genre_client}}">
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <button type="submit" class="btn btn-success">Salvar</button>
            <button class="btn btn-info" href="{{route('client.index')}}">Voltar</button>
          </div>
        </div>
    </form>
  </div>
</body>
</html>

resources/views/client/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <title>Crud Cliente</title>
</head>
<body>
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Nome</th>
          <th scope="col">Gênero</th>
          <th scope="col">
            <a class="btn btn-success" href="{{route('client.create')}}">Adicionar Cliente</a>
            <a class="btn btn-info" href="{{route('document.index')}}">Lista Documento</a>
          </th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        @foreach($clients as $client)
          <tr>
            <th scope="row">{{$client->id}}</th>
            <td>{{$client->name_client}}</td>
            <td>{{$client->genre_client}}</td>
            <td>
              <a class="btn btn-warning" href="{{ route('client.edit', $client->id) }}">Editar Cliente</a>
            </td>
            <td>
              <form method="POST" action="{{route('client.destroy', $client->id)}}">
                {{ method_field('DELETE') }}
                {{ csrf_field() }}
                <button type="submit" class="btn btn-danger">Deletar Cliente</button>
              </form>
            </td>
            <td>
              <a class="btn btn-info" href="{{ route('document.index') }}">Add Documento</a>
            </td>
          </tr>
        @endforeach
      </tbody>
    </table>
</body>
</html>

resources/views/document/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <title>Crud Cliente</title>
</head>
<body>
  <div class="container">
    <div class="">
      <form action="{{route('document.store')}}" method="POST" enctype="multipart/form-data">
      {{ csrf_field() }}

          <div class="col-md-6">
            <div class="form-group">
              <h1>Cadastrar Documento</h1>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label for="type_document">Tipo de Documento</label>
              <input type="text" class="form-control" id="type_document" placeholder="Tipo de Documento" name="type_document">
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label for="number_document">Número Documento</label>
              <input type="text" class="form-control" id="number_document" placeholder="Número Documento" name="number_document">
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label for="document_client">Id Cliente</label>
              <input type="text" class="form-control" id="document_client" name="document_client">
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <button type="submit" class="btn btn-success">Salvar</button>
              <button class="btn btn-info" href="{{route('client.index')}}">Voltar</button>
            </div>
          </div>
      </form>
    </div>
  </div>
</body>
</html>

resources/views/document/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <title>Edit Document</title>
</head>
<body>
  <div class="container">
    <form method="post" action="{{route('document.update', $document->id)}}" enctype="multipart/form-data">
        {!! method_field('put') !!}
        {{ csrf_field() }}

        <div class="col-md-6">
          <div class="form-group">
            <h1>Cliente</h1>
          </div>
        </div>

        <!-- <input type="hidden" name="id_client" value="$client->id"> -->

        <div class="col-md-6">
          <div class="form-group">
            <h1>Edit Document</h1>
          </div>
        </div>

        <div class="col-md-6">
          <div class="form-group">
            <label for="type_document">Tipo de Documento</label>
            <input type="text" class="form-control" id="type_document" name="type_document" value="{{$document->type_document}}">
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label for="number_document">Número Documento</label>
            <input type="text" class="form-control" id="number_document" name="number_document" value="{{$document->number_document}}">
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label for="document_client">Id Cliente</label>
            <input type="text" class="form-control" id="document_client" name="document_client" value="{{$document->document_client}}">
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <button type="submit" class="btn btn-success">Salvar</button>
            <button class="btn btn-info" href="{{route('client.index')}}">Voltar</button>
          </div>
        </div>
    </form>
  </div>
</body>
</html>

resources/views/document/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <title>Crud Documento</title>
</head>
<body>
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Id Documento</th>
          <th scope="col">Id Cliente</th>
          <th scope="col">Tipo Documento</th>
          <th scope="col">Número Documento</th>
          <th scope="col">
            <a class="btn btn-info" href="{{route('client.index')}}">Voltar ao cliente</a>
          </th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        @foreach($documents as $document)
          <tr>
            <th scope="row">{{ $document->id }}</th>
            <td>{{$document->document_client }}</td>
            <td>{{$document->type_document}}</td>
            <td>{{$document->number_document}}</td>
            <td>
              <a class="btn btn-warning" href="{{ route('document.edit', $document->id) }}">Editar</a>
            </td>
            <td>
              <form method="POST" action="{{route('document.destroy', $document->id)}}">
                {{ method_field('DELETE') }}
                {{ csrf_field() }}
                <button type="submit" class="btn btn-danger">Deletar</button>
              </form>
            </td>
          </tr>
        @endforeach
      </tbody>
    </table>
</body>
</html>